import json
from models import AgentConfigModel
from api.schemas import AgentConfig

def db_to_pydantic_agent(a: AgentConfigModel) -> AgentConfig:
    """Converte um modelo SQLAlchemy AgentConfigModel para o schema Pydantic AgentConfig."""
    return AgentConfig(
        id=a.id,
        name=a.name,
        description=a.description,
        model=a.model,
        fallback_model=a.fallback_model,
        temperature=a.temperature,
        top_p=a.top_p,
        top_k=a.top_k,
        presence_penalty=a.presence_penalty,
        frequency_penalty=a.frequency_penalty,
        safety_settings=a.safety_settings,
        model_settings=json.loads(a.model_settings) if a.model_settings else {},
        is_active=a.is_active,
        date_awareness=a.date_awareness,
        system_prompt=a.system_prompt,
        context_window=a.context_window,
        knowledge_base=json.loads(a.knowledge_base) if a.knowledge_base else [],
        knowledge_base_id=a.knowledge_base_id,
        knowledge_base_ids=[kb.id for kb in a.knowledge_bases],
        rag_retrieval_count=a.rag_retrieval_count,
        rag_translation_enabled=a.rag_translation_enabled,
        rag_multi_query_enabled=a.rag_multi_query_enabled,
        rag_rerank_enabled=a.rag_rerank_enabled,
        rag_agentic_eval_enabled=a.rag_agentic_eval_enabled,
        rag_parent_expansion_enabled=a.rag_parent_expansion_enabled,
        tool_ids=[t.id for t in a.tools],
        simulated_time=a.simulated_time,
        security_competitor_blacklist=a.security_competitor_blacklist,
        security_forbidden_topics=a.security_forbidden_topics,
        security_discount_policy=a.security_discount_policy,
        security_language_complexity=a.security_language_complexity,
        security_pii_filter=a.security_pii_filter,
        security_validator_ia=a.security_validator_ia,
        security_bot_protection=a.security_bot_protection,
        security_max_messages_per_session=a.security_max_messages_per_session,
        security_semantic_threshold=a.security_semantic_threshold,
        security_loop_count=a.security_loop_count,
        ui_primary_color=a.ui_primary_color,
        ui_header_color=a.ui_header_color,
        ui_chat_title=a.ui_chat_title,
        ui_welcome_message=a.ui_welcome_message,
        initial_message=a.initial_message,
        initial_question_message=a.initial_question_message,
        initial_ignore_message=a.initial_ignore_message,
        inbox_capture_enabled=a.inbox_capture_enabled,
        router_enabled=a.router_enabled,
        router_simple_model=a.router_simple_model,
        router_complex_model=a.router_complex_model,
        handoff_enabled=a.handoff_enabled,
        response_translation_enabled=a.response_translation_enabled,
        response_translation_fallback_lang=a.response_translation_fallback_lang or "portuguese"
    )
