"""add_transcription_folders

Revision ID: 047a924d0aca
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 12:21:13.434927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '047a924d0aca'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table already exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'transcription_folders' not in tables:
        op.create_table('transcription_folders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transcription_folders_id'), 'transcription_folders', ['id'], unique=False)
    
    if 'background_process_logs' in tables:
        op.drop_index('ix_background_process_logs_id', table_name='background_process_logs')
        op.drop_index('ix_background_process_logs_task_id', table_name='background_process_logs')
        op.drop_table('background_process_logs')
    
    # Defensive drop columns
    columns_agent_config = [c['name'] for c in inspector.get_columns('agent_config')]
    if 'web_browsing_scope' in columns_agent_config:
        op.drop_column('agent_config', 'web_browsing_scope')
    if 'web_browsing_enabled' in columns_agent_config:
        op.drop_column('agent_config', 'web_browsing_enabled')
    if 'web_browsing_rules' in columns_agent_config:
        op.drop_column('agent_config', 'web_browsing_rules')
    
    # Defensive drop indexes
    indexes_ki = [i['name'] for i in inspector.get_indexes('knowledge_items')]
    for idx_name in ['idx_ki_fts_en', 'idx_ki_fts_es', 'idx_ki_fts_pt', 'idx_ki_fts_simple']:
        if idx_name in indexes_ki:
            op.drop_index(idx_name, table_name='knowledge_items', postgresql_using='gin')

    op.alter_column('support_requests', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    
    if 'ix_support_requests_id' in [i['name'] for i in inspector.get_indexes('support_requests')]:
        op.drop_index('ix_support_requests_id', table_name='support_requests')
    if 'ix_support_requests_session_id' in [i['name'] for i in inspector.get_indexes('support_requests')]:
        op.drop_index('ix_support_requests_session_id', table_name='support_requests')
    
    # Defensive add column
    columns_transcription_tasks = [c['name'] for c in inspector.get_columns('transcription_tasks')]
    if 'folder_id' not in columns_transcription_tasks:
        op.add_column('transcription_tasks', sa.Column('folder_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'transcription_tasks', 'transcription_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    
    # Defensive drop index
    indexes_user_memory = [i['name'] for i in inspector.get_indexes('user_memory')]
    if 'idx_user_memory_key' in indexes_user_memory:
        op.drop_index('idx_user_memory_key', table_name='user_memory')
    if 'idx_user_memory_session' in indexes_user_memory:
        op.drop_index('idx_user_memory_session', table_name='user_memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_memory_session', 'user_memory', ['session_id'], unique=False)
    op.create_index('idx_user_memory_key', 'user_memory', ['key'], unique=False)
    op.drop_constraint(None, 'transcription_tasks', type_='foreignkey')
    op.drop_column('transcription_tasks', 'folder_id')
    op.create_index('ix_support_requests_session_id', 'support_requests', ['session_id'], unique=False)
    op.create_index('ix_support_requests_id', 'support_requests', ['id'], unique=False)
    op.alter_column('support_requests', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('idx_ki_fts_simple', 'knowledge_items', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(question, ''::text) || ' '::text) || COALESCE(answer, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_ki_fts_pt', 'knowledge_items', [sa.text("to_tsvector('portuguese'::regconfig, (COALESCE(question, ''::text) || ' '::text) || COALESCE(answer, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_ki_fts_es', 'knowledge_items', [sa.text("to_tsvector('spanish'::regconfig, (COALESCE(question, ''::text) || ' '::text) || COALESCE(answer, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('idx_ki_fts_en', 'knowledge_items', [sa.text("to_tsvector('english'::regconfig, (COALESCE(question, ''::text) || ' '::text) || COALESCE(answer, ''::text))")], unique=False, postgresql_using='gin')
    op.add_column('agent_config', sa.Column('web_browsing_rules', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_config', sa.Column('web_browsing_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('agent_config', sa.Column('web_browsing_scope', sa.VARCHAR(), server_default=sa.text("'all'::character varying"), autoincrement=False, nullable=True))
    op.create_table('background_process_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('process_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='background_process_logs_pkey')
    )
    op.create_index('ix_background_process_logs_task_id', 'background_process_logs', ['task_id'], unique=False)
    op.create_index('ix_background_process_logs_id', 'background_process_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_transcription_folders_id'), table_name='transcription_folders')
    op.drop_table('transcription_folders')
    # ### end Alembic commands ###
